### ISSUE TITLE
Behaviour on different platforms?

### ISSUE THREAD

**Issue by masus04** [Rexios80/wear_ongoing_activity#1]
Thank you very much for providing this implementation, I'm looking forward to testing it for my use case!

Before doing so, I was wondering how the package behaves when launched on any platform other than wearOS, such as Android mobile.

Is the ongoing activity simply ignored, or can it be turned into a regular notification?

**Comment by Rexios80** [comment]
I haven't tested it but it probably won't work. You could use something like the is_wear package to check if the code is running on WearOS before starting the activity.

**Comment by masus04** [comment]
Can confirm that package breaks on android mobile. I'll update this comment once I figured out how to handle it.
