### ISSUE TITLE
Downgrade to API level 33

### ISSUE THREAD

**Issue by DanielMartini** [Rexios80/wear_ongoing_activity#3]
Hello,

First of all, thanks for this package, it's a must right now for Wear Os apps deployments,

But as it aims to be just for Wear OS and not Android in general, I think it should be downgraded to the last permitted API level, that in this case is 33.

![image](https://github.com/Rexios80/wear_ongoing_activity/assets/8677856/bef21504-b984-4f8e-9fdb-2b1e2dd43b24)

[https://developer.android.com/google/play/requirements/target-sdk](https://developer.android.com/google/play/requirements/target-sdk)

it's not possible to make releases for Wear Os with greater versions right now.

Regards

**Comment by Rexios80** [comment]
I'm not exactly sure why you can't target SDK 34 when WearOS 34 definitely exists, but if that's what the Play Store says then I'll make it work

**Comment by DanielMartini** [comment]
I do not know either, to be honest, I noticed about it because a message popped on the play console saying that API level 34 was not permitted when I tried to make a release to production 🤷

**Comment by Rexios80** [comment]
Released in version 0.1.3
